// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

'use client';
import dynamic from 'next/dynamic';
import './globals.css';
import { Poppins } from 'next/font/google';
// import WalletContextProvider from '@/app/context/WalletConnectionProvider';
// import { Metadata } from 'next';

const poppins = Poppins({ subsets: ['latin'], weight: '500' });

// export const metadata: Metadata = {
//   title: 'Ecotoken',
//   description: "ReFi Dapp that makes investors and NGO's come together",
// };

const WalletConnectionProvider = dynamic(
  () => import('./context/WalletConnectionProvider'),
  { ssr: false }
);
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        {/* <WalletContextProvider>{children}</WalletContextProvider> */}
        <WalletConnectionProvider>{children}</WalletConnectionProvider>
      </body>
    </html>
  );
}
